networks:
  kafka_network:
    driver: bridge

services:
  kafka-0:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka-0
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-0:29093,2@kafka-1:29093,3@kafka-2:29093
      KAFKA_LISTENERS: INTERNAL://kafka-0:9092,CONTROLLER://kafka-0:29093,EXTERNAL://0.0.0.0:19092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-0:9092,EXTERNAL://localhost:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
      KAFKA_CFG_LOG_RETENTION_HOURS: "1"
      KAFKA_CFG_MESSAGE_MAX_BYTES: "2097152"         # 2 MB
      KAFKA_CFG_REPLICA_FETCH_MAX_BYTES: "2097152"
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "false"
    volumes:
      - ./kafka0-data:/var/lib/kafka/data
    networks:
      - kafka_network
    ports:
      - 19092:19092

  kafka-1:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka-1
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-0:29093,2@kafka-1:29093,3@kafka-2:29093
      KAFKA_LISTENERS: INTERNAL://kafka-1:9092,CONTROLLER://kafka-1:29093,EXTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-1:9092,EXTERNAL://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
    volumes:
      - ./kafka1-data:/var/lib/kafka/data
    networks:
      - kafka_network
    ports:
      - 29092:29092

  kafka-2:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka-2
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka-0:29093,2@kafka-1:29093,3@kafka-2:29093
      KAFKA_LISTENERS: INTERNAL://kafka-2:9092,CONTROLLER://kafka-2:29093,EXTERNAL://0.0.0.0:39092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka-2:9092,EXTERNAL://localhost:39092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      CLUSTER_ID: "MkU3OEVBNTcwNTJENDM2Qk"
    volumes:
      - ./kafka2-data:/var/lib/kafka/data
    networks:
      - kafka_network
    ports:
      - 39092:39092

  console:
    container_name: kafka-console
    image: redpandadata/console:v3.2.2
    networks:
      - kafka_network
    environment:
      KAFKA_BROKERS: kafka-0:9092,kafka-1:9092,kafka-2:9092
    ports:
      - 8080:8080
    depends_on:
      - kafka-0
      - kafka-1
      - kafka-2

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: webhooks
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d webhooks" ]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pg_data:
